runtime: python
service: replenishment-optimization-new
env: flex
entrypoint: python main.py

runtime_config:
  python_version: 3

resources:
  cpu: 4
  memory_gb: 5.6
  disk_size_gb: 10
  volumes:
  - name: ramdisk1
    volume_type: tmpfs
    size_gb: 0.5
